const events = [
  {
    title: "Nritta",
    description:
      "Anticipate an electrifying spectacle of dance at the grand event, 'Nritta.' Elevate your performance as a solo artist or collaborate in a duo, and let the stage be your canvas for up to 5 minutes of captivating expression.  Make every moment count and immerse yourself in the rhythmic world of 'Nritta.' The spotlight awaits, so get ready to leave an indelible mark on the stage with your dance prowess.",
    prizePool: 30000,
    eventId: 1,
    image: "../assets/banner.png",
    rules:["No Vulgarity.","No use of props which litter the stage, such as colors.","Use of any props to be informed beforehand. Soundtrack also to be provided beforehand.","No professional dancers, only college students.","3-5 minutes per performance.","All dance styles and fusion dance is permitted.","Venue (tentative) - Basketball Court "],
    contacts:[{name:"Aditya Nangarath",number:"7022271553"},{name:"Bysani Akshaya",number:"7799008583"}],
    spocs: ["Aditya Nangarath", "Bysani Akshaya"],
  },
  {
    title: "Blitz",
    description:
      "An unconventional debate format which does not follow the quintessential rules of the Asian and European Parliamentary system",
    prizePool: 4500,
    eventId: "2",
    spocs: [],
  },
  {
    title: "Brush Up",
    description:
      "Participants step into their imagination and splash their thoughts on their canvases",
    prizePool: 6000,
    eventId: "3",
    spocs: ["Vrajnandak Nangunoori", "Hemang Seth"],
    contacts: ["8817972743", "9059408976"],
  },
  {
    title: "Ramp It Up",
    description:
      "Designers and models line up to flaunt their beauty mesmerising the audience.",
    prizePool: 10000,
    eventId: "4",
    spocs: ["H Sanjeev", "Shreya Chavan"],
    contacts: ["9491370927", "9347425563"],
  },
  {
    title: "League of Fanatics",
    description:
      "Four tracks of mind-boggling Pop  Trivia quizzes all lead to one final stage of cerebration, testing your knowledge and wit",
    prizePool: 10000,
    eventId: "5",
    spocs: ["Harsh Modani", "R Harshavardhan"],
    contacts: ["9380126399", "9645894725"],
  },
  {
    title: "Battle of Bands",
    description:
      "Battalions of music enthusiasts come together to mesmerise us with their brilliant vocals and instrumental performances.",
    prizePool: 25000,
    eventId: "6",
    spocs: ["Karanveer Singh", "Saket Gurjar"],
    contacts: ["6268463824", "8502883397"],
  },
  {
    title: "Case in Point",
    description:
      "Explore your entrepreneurship skills by posing as the owner of a famous company and showcase what you would have done differently to change the course of the company",
    prizePool: 13000,
    eventId: "7",
    spocs: ["Karthik Reddy"],
    contacts: ["7795933534"],
  },
  {
    title: "Nukkad Naatak",
    description:
      "Theatrical/Drama face-off between student teams displaying their drama prowess",
    prizePool: 12000,
    eventId: "8",
    spocs: ["Aaditya", "Chandrima"],
    contacts: ["7972513736", "9028872476"],
  },
  {
    title: "Rang Manch",
    description:
      "Theatrical/Drama face-off between student teams displaying their drama prowess",
    prizePool: 20000,
    eventId: "9",
    spocs: ["Arjun Subhedar", "Divyansh Singhal"],
    contacts: ["77028770201", "7023333611"],
  },
  {
    title: "Sargam",
    description:
      "Battalions of music enthusiasts come together to mesmerise us with their brilliant vocals and instrumental performances.",
    prizePool: 10000,
    eventId: "10",
    spocs: ["Rishabh Dixit", "Veddant M"],
    contacts: ["6366258170", "7588069853"],
  },
  {
    title: "Codm",
    description:
      "Welcome to IIITBs rendition of the CODM World Championship. Battle it out in team deathmatch to claim top cash prizes. ",
    prizePool: 3000,
    eventId: "11",
    spocs: ["Prasanth Kumar", "Sasank Karamsetty"],
    contacts: [""],
  },
  {
    title: "Jijnasa",
    description: "",
    prizePool: 3000,
    eventId: "12",
    spocs: ["Amar Pratap Singh", "Dhruv Gupta"],
    contacts: ["8197367978", "9015346166"],
  },
  {
    title: "Slam poetry",
    description: "",
    prizePool: 4000,
    eventId: "13",
    spocs: ["Ayush Gupta"],
    contacts: ["8884803648"],
  },
  {
    title: "Lost in Action",
    description: "",
    prizePool: 4000,
    eventId: "14",
    spocs: ["Vyom Sharma", "Bhavjyot Singh"],
    contacts: ["7060886758", "9855498265"],
  },
  {
    title: "Cards Against Humanity",
    description: "",
    prizePool: 4000,
    eventId: "15",
    spocs: ["Pranav Vajreshwari"],
  },
  {
    title: "JAM",
    description: "",
    prizePool: 8000,
    eventId: "16",
    spocs: ["Vishruth Vijay", "Vikas Kalyanapuram"],
    contacts: ["9449960095", "8762175731"],
  },
  {
    title: "Math puzzle",
    description: "",
    prizePool: 3000,
    eventId: "17",
    spocs: [],
  },
  {
    title: "Vedanta Darshana",
    description: "",
    prizePool: 3000,
    eventId: "18",
    spocs: ["Amar Pratap Singh", "Dhruv Gupta"],
    contacts: ["8197367978", "9015346166"],
  },
  {
    title: "Gulp and Gobble",
    description: "",
    prizePool: 3000,
    eventId: "19",
    spocs: [],
    contacts: [],
  },
  {
    title: "FIFA",
    description: "",
    prizePool: 4000,
    eventId: "20",
    spocs: ["Keshav Goyal", "Siddharth Ayathu"],
    contacts: ["8968076237", "6366281143"],
  },
  {
    title: "Valorant",
    description: "",
    prizePool: 4000,
    eventId: "21",
    spocs: ["Brij Desai", "Harshith Reddy"],
    contacts: ["6362043016", "9177785261"],
  },
  {
    title: "BGMI",
    description: "",
    prizePool: 3000,
    eventId: "22",
    spocs: ["Pushkar Kulkarni", "Kunal Narang"],
    contacts: ["9136815683", "9012252500"],
  },
  {
    title: "Clash Royale",
    description: "",
    prizePool: 2000,
    eventId: "23",
    spocs: ["Narayana Srimanth"],
    contacts: ["9032959454"],
  },
  {
    title: "Infinitude",
    description: "",
    prizePool: 20000,
    eventId: "24",
    spocs: ["Nupur Patil", "Shiven Phogat"],
    contacts: ["9922709459", "9137231118"],
  },
  {
    title: "Cut to the Chase",
    description: "",
    prizePool: 12000,
    eventId: "25",
    spocs: ["Varshith Vattikuti", "Nathan Mathew Verghese"],
    contacts: ["9886987649", "8848839946"],
  },
  {
    title: "Photo Competition",
    description: "",
    prizePool: 5000,
    eventId: "26",
    spocs: ["M Srinivasan", "Vaibhav Thapliyal"],
    contacts: ["9353738745", "8128818422"],
  },
];

export default events;
